--DROP TABLE "PECA_USADA";
--DROP TABLE "PECA";
--DROP TABLE "ORDEM_SERVICO";
--DROP TABLE "MECANICO";
--DROP TABLE "VEICULO";
--DROP TABLE "CLIENTES";

CREATE TABLE "CLIENTES"
        ("COD_CLIENTE" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
        "NOME" VARCHAR(150),
        "CPF" VARCHAR(15) UNIQUE,
        "RG" VARCHAR(13));

CREATE TABLE "VEICULO"
        ("COD_VEICULO" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
        "PLACA" VARCHAR(8),
        "MARCA" VARCHAR(150),
        "MODELO" VARCHAR (150),
        "COD_CLIENTE_FK" INT NOT NULL,
        FOREIGN KEY ("COD_CLIENTE_FK") REFERENCES "CLIENTES" ("COD_CLIENTE"));

CREATE TABLE "MECANICO"
        ("COD_MECANICO" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
        "NOME" VARCHAR(150),
        "CPF" VARCHAR(15) UNIQUE,
        "RG" VARCHAR(13));

CREATE TABLE "ORDEM_SERVICO"
        ("COD_ORDEM_SERVICO" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
        "DATA" DATE,
        "DESCRICAO" VARCHAR(150),
        "VALOR_MAO_OBRA" DOUBLE,
        "COD_VEICULO_FK" INT NOT NULL,
        "COD_MECANICO_FK" INT NOT NULL,
        FOREIGN KEY ("COD_VEICULO_FK") REFERENCES "VEICULO" ("COD_VEICULO"),
        FOREIGN KEY ("COD_MECANICO_FK") REFERENCES "MECANICO" ("COD_MECANICO"));

CREATE TABLE "PECA"
        ("COD_PECA" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
        "DESCRICAO" VARCHAR(150),
        "PRECO_COMPRA" DOUBLE,
        "PRECO_VENDA" DOUBLE);

CREATE TABLE "PECA_USADA"
        ("COD_PECA_USADA" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
        "COD_ORDEM_SERVICO_FK" INT NOT NULL,
        "COD_PECA_FK" INT NOT NULL,
        "QUANTIDADE" INT,
        FOREIGN KEY ("COD_ORDEM_SERVICO_FK") REFERENCES "ORDEM_SERVICO" ("COD_ORDEM_SERVICO"),
        FOREIGN KEY ("COD_PECA_FK") REFERENCES "PECA" ("COD_PECA"));

INSERT INTO "CLIENTES" ("NOME", "CPF", "RG") VALUES ('Bruno', '010.047.109-92', '42.623.445-5'), ('Marihelly', '073.562.839-48', '5.464.383-0');
INSERT INTO "VEICULO" ("PLACA", "MARCA", "MODELO", "COD_CLIENTE_FK") VALUES ('IHW-0593', 'GM', 'Vectra', 1), ('MIN-8687', 'Honda', 'Biz 125', 2);
INSERT INTO "MECANICO" ("NOME", "CPF", "RG") VALUES ('Osvaldo', '222.333.444-55', '45.554.658-56'), ('Vilson', '777.888.999-00', '4.563.458-5');
INSERT INTO "ORDEM_SERVICO" ("DATA", "DESCRICAO", "VALOR_MAO_OBRA", "COD_VEICULO_FK", "COD_MECANICO_FK") VALUES
                            ('2013-06-15', 'Caiu a roda', 150.50, 1, 2), ('2013-06-17', 'Correia solta', 30.50, 2, 1);
INSERT INTO "PECA" ("DESCRICAO", "PRECO_COMPRA", "PRECO_VENDA") VALUES ('Parafuso', 1.50, 2.30), ('Correia', 95.10, 140.50);
INSERT INTO "PECA_USADA" ("COD_ORDEM_SERVICO_FK", "COD_PECA_FK", "QUANTIDADE") VALUES (1, 1, 4), (2, 2, 1), (2, 1, 2);
